# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

enigma_version=3.0.0
unpick_version=3.0.0-beta.11
cfr_version=0.2.2
vineflower_version=1.11.1
asm_version=9.8
gson_version=2.10.1

# Javadoc generation/linking
fabric_loader_version=0.16.10
jetbrains_annotations_version=24.1.0

# Build logic
tiny_remapper_version=0.10.4
junit_version=5.11.0
assertj_version=3.26.3
