name: Update Base Branch

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  update:
    if: ${{ github.event.label.name == 'update-base' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: FabricMC/fabric-action-scripts@v2
        with:
          context: yarn-update-base